# Generated by Django 4.2.1 on 2023-05-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BOOK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField(max_length=100, unique=True)),
                ("Category", models.TextField(max_length=100)),
                ("Author", models.TextField(max_length=100)),
                ("ImportPrice", models.IntegerField()),
                ("Amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="IMPORTLOG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ImportDate", models.DateTimeField()),
                ("PrevAmount", models.IntegerField()),
                ("Amount", models.IntegerField()),
                ("UpdatedAmount", models.IntegerField()),
                ("TotalPrice", models.IntegerField()),
                (
                    "Book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="book.book"
                    ),
                ),
            ],
        ),
    ]
