# Generated by Django 4.2.1 on 2023-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="PrevAmount",
            field=models.IntegerField(default=0),
        ),
    ]
