# Generated by Django 4.2.1 on 2023-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_importlog_prevamount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="UpdatedAmount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
