# Generated by Django 4.2.1 on 2023-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="PrevAmount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="UpdatedAmount",
            field=models.IntegerField(default=0),
        ),
    ]
