# Generated by Django 4.2.1 on 2023-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_importlog_prevamount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CONSTRAINT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MinImport", models.IntegerField(default=150)),
                ("AmountNeedImport", models.IntegerField(default=300)),
                ("MaxDebt", models.IntegerField(default=1000000)),
                ("BookAmountAfter", models.IntegerField(default=20)),
                ("PaidNotGreaterThanDebt", models.BooleanField(default=True)),
            ],
        ),
    ]
