# Generated by Django 4.2.1 on 2023-05-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="TotalPrice",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
