# Generated by Django 4.2.1 on 2023-05-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BILL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BillDate", models.DateTimeField()),
                ("TotalPrice", models.IntegerField()),
                ("Paid", models.IntegerField()),
                ("Debt", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CUSTOMER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.TextField(max_length=100)),
                ("Address", models.TextField(blank=True, max_length=100, null=True)),
                ("PhoneNumber", models.TextField(max_length=100, unique=True)),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Debt", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DEBTLOG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DebtDate", models.DateTimeField()),
                ("PrevDebt", models.IntegerField()),
                ("Paid", models.IntegerField()),
                ("UpdatedDebt", models.IntegerField()),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customer.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BILLDETAIL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Amount", models.IntegerField()),
                ("SoldPrice", models.IntegerField()),
                (
                    "Bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="customer.bill"
                    ),
                ),
                (
                    "Book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="book.book"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="Customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="customer.customer"
            ),
        ),
    ]
