# Generated by Django 4.2.1 on 2023-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_phonenumber_alter_debtlog_prevdebt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="Debt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
