# Generated by Django 4.2.1 on 2023-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_customer_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billdetail",
            name="Amount",
            field=models.IntegerField(default=0),
        ),
    ]
